# Project
version=21.1
group=net.darkhax.openloader
java_version=21

# Mod
mod_name=OpenLoader
mod_author=Darkhax
mod_id=openloader
mod_license=LGPL 2.1
mod_description=An open source loader for custom resources and data!
mod_repo=https://github.com/Darkhax-Minecraft/Open-Loader
mod_docs=https://docs.darkhax.net/mods/open-loader
mod_item_icon=minecraft:command_block

# Build Flags
mod_client_only=false

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
prickle_version=21.1.4
prickle_version_range=[21.1, 21.2)
jei_version=19.18.10.218
crt_version=21.0.3

# NeoForge
neoforge_version=21.1.133
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.115.1+1.21.1
fabric_loader_version=0.16.10
modmenu_version=11.0.2

# Forge
forge_version=52.0.16
forge_loader_version_range=[52,)
forge_version_range=[52.0.16,)

# CurseForge
curse_project=354339
curse_page=https://www.curseforge.com/minecraft/mc-mods/open-loader

# Modrinth
modrinth_project=KwWsINvD
modrinth_page=https://modrinth.com/mod/open-loader

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false