# Project
version=22.1
group=net.darkhax.openloader

# Common
minecraft_version=1.21

# Forge
forge_version=51.0.18

# NeoForge
neoforge_version=21.0.38-beta
neoforge_version_range=21.0,

# Fabric
fabric_version=0.100.4+1.21
fabric_loader_version=0.15.11

# Mod options
mod_name=OpenLoader
mod_author=Darkhax
mod_id=openloader
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/open-loader
mod_source=https://github.com/Darkhax-Minecraft/Open-Loader
mod_issues=https://github.com/Darkhax-Minecraft/Open-Loader/issues
mod_description=An open source data and resource loader.
mod_license=LGPL V2.1
mod_twitter=https://twitter.com/DarkhaxDev
mod_discord=https://discord.darkhax.net

# Gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# CurseForgeGradle
curse_project=354339

# Modrinth
modrinth_project=KwWsINvD