# Project
version=26.2.0.1
group=net.darkhax.openloader
java_version=25

# Mod
mod_name=OpenLoader
mod_author=Darkhax
mod_id=openloader
mod_license=LGPL 2.1
mod_description=An open source loader for custom resources and data!
mod_repo=https://github.com/Darkhax-Minecraft/Open-Loader
mod_docs=https://docs.darkhax.net/mods/open-loader
mod_item_icon=minecraft:command_block

# Build Flags
mod_client_only=false

# Common
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-2
prickle_version=26.2.0.3
prickle_version_range=[26.2.0.3, 26.3)

# NeoForge
neoforge_version=26.2.0.41-beta

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3

# CurseForge
curse_project=354339
curse_page=https://www.curseforge.com/minecraft/mc-mods/open-loader

# Modrinth
modrinth_project=KwWsINvD
modrinth_page=https://modrinth.com/mod/open-loader

# Gradle
org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.workers.max=2
