modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Open-Loader/issues"

[[mods]]
modId="openloader"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.openloader]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15]"
    ordering="NONE"
    side="BOTH"