modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Open-Loader/issues"
license = "LGPL 2.1"

[[mods]]
modId="openloader"
updateJSONURL="https://updates.blamejared.com/get?n=openloader&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.openloader]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"