modLoader="javafml"
loaderVersion="[37,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Open-Loader/issues"
license = "LGPL v2.1"

[[mods]]
modId="openloader"
updateJSONURL="https://updates.blamejared.com/get?n=openloader&gv=1.17.1"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:book"

[[dependencies.openloader]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.81,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.openloader]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"